#!/usr/bin/env Rscript
main <- function() {
  import(commandArgs(TRUE)[[1]])
}

extra <- list(
  "2022" = list(
    d13 = "rich-no-recursion.R",
    d22 = "rich.md"))

replace <- function(path, subs) {
  code <- readLines(path)
  for (i in seq_along(subs)) {
    code <- sub(names(subs)[[i]], subs[[i]], code, fixed = TRUE)
  }
  code
}

import <- function(src, dest = ".") {
  year <- gsub("[^0-9]", "", src)

  path <- file.path(dest, year)
  unlink(path, recursive = TRUE)
  dir.create(path, FALSE, TRUE)

  if (as.integer(year) <= 2022) {
    import_old(year, src, dest)
  } else {
    import_new(year, src, dest)
  }
}

import_old <- function(year, src, dest) {
  path <- file.path(dest, year)
  for (p in dir(src, pattern = "d[0-9]{2}", full.names = TRUE)) {
    name <- switch(year,
                   "2020" = "rich-script.R",
                   "2018" = "richfitz.R",
                   "rich.R")
    test_prefix <- switch(year,
                          "2022" = "test-input",
                          "2021" = "rich-test",
                          "2020" = "rich-test",
                          "2018" = "richfitz-test-input",
                          stop("Unknown pattern for this year"))
    if (file.exists(file.path(p, name))) {
      day <- basename(p)
      message(sprintf("Importing %s", day))
      input_txt <- sprintf("input-%s.txt", day)
      file.copy(file.path(p, "rich-input.txt"), file.path(path, input_txt),
                overwrite = TRUE)

      subs <- c("rich-input.txt" = input_txt)

      test <- dir(p, sprintf("%s.*\\.txt", test_prefix), full.names = TRUE)
      test_dest <- sub(test_prefix, sprintf("test-input-%s", day),
                       basename(test))
      if (length(test_dest) == 1) {
        test_dest <- sub("-1", "", test_dest)
      }
      file.copy(test, file.path(path, test_dest), overwrite = TRUE)
      subs[basename(test)] <- test_dest

      writeLines(replace(file.path(p, name), subs),
                 file.path(path, paste0(day, ".R")))
      for (f in extra[[year]][[day]]) {
        writeLines(replace(file.path(p, f), subs),
                   file.path(path, sprintf("%s-%s", day, sub("rich-", "", f))))
      }
    }
  }
}


import_new <- function(year, src, dest) {
  path <- file.path(dest, year)
  for (p in dir(src, pattern = "d[0-9]{2}", full.names = TRUE)) {
    path_py <- file.path(p, "rich.py")
    path_r <- file.path(p, "rich.r")
    if (file.exists(path_py) || file.exists(path_r)) {
      day <- basename(p)
      code <- c(if (file.exists(path_py)) readLines(path_py) else NULL,
                if (file.exists(path_r)) readLines(path_r) else NULL)
      re <- '".*\\.txt"'
      code <- code[grepl(re, code)]
      m <- gregexpr(re, code)
      i <- rep(seq_along(m), lengths(m))
      j <- unlist(m)
      k <- j + unlist(lapply(m, attr, "match.length")) - 1

      files_from <- unique(substr(code[i], j + 1, k - 1))
      files_to <- files_from
      files_to[files_to == "rich-input.txt"] <- sprintf("input-%s.txt", day)
      files_to[files_to == "test.txt"] <- sprintf("test-input-%s.txt", day)
      files_to <- sub("test([0-9])\\.txt",
                      sprintf("test-input-%s-\\1.txt", day),
                      files_to)

      file.copy(file.path(p, files_from),
                file.path(path, files_to), overwrite = TRUE)

      subs <- setNames(files_to, files_from)
      if (file.exists(path_py)) {
        writeLines(replace(path_py, subs),
                   file.path(path, paste0(day, ".py")))
      }
      if (file.exists(path_r)) {
        writeLines(replace(path_r, subs),
                   file.path(path, paste0(day, ".R")))
      }
    }
  }
}

if (!interactive()) {
  main()
}
